site_name: Hylé Developer Hub
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    primary: custom
  features:
    - navigation.indexes
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
copyright: Copyright &copy; 2024 Hylé
extra:
  social:
    - icon: fontawesome/brands/github
      link: http://github.com/hyle-org/
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/hyle_org
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/hyl-/
    - icon: fontawesome/solid/archway
      link: https://warpcast.com/hyle-org
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Hyl%C3%A9-org
    - icon: fontawesome/brands/telegram
      link: https://t.me/hyle_org
plugins:
    - search
    - awesome-pages
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
repo_url: https://github.com/Hyle-org/hyle-cosmos
