site_name: Hyli Developer Hub
site_url: https://docs.hyli.org
theme:
  name: material
  custom_dir: 'overrides'
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: Roboto
  palette:
    primary: custom
  features:
    - navigation.sections # section titles in left-hand menu
    - navigation.indexes # clickable section titles in left-hand menu
    - navigation.expand # expand sub-menus (re-enable if header tabs)
  #  - navigation.tabs # to have header tabs
    - navigation.prune # html minimization
  #  - toc.integrate # toc in left-hand sidebar
    - content.code.copy
  #  - navigation.footer

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/neoteroi-mkdocs.css
  - assets/stylesheets/neoteroi-timeline.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - neoteroi.timeline

plugins:
  - search
  - awesome-pages
  - mkdocs-video
  - privacy
  - social:
      enabled: true
      cards_layout_options:
        background_color: "#1E2933"
        font_family: Chakra Petch
        color: "#DF6445"

copyright: Copyright &copy; 2025 Hyli

extra:
  social:
    - icon: fontawesome/brands/github
      link: http://github.com/hyli-org/
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/hyli_org
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/hyl-/
    - icon: fontawesome/solid/archway
      link: https://warpcast.com/hyle-org
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Hyl%C3%A9-org
    - icon: fontawesome/brands/telegram
      link: https://t.me/hyle_org

repo_url: https://github.com/Hyli-org/hyli
