site_name: Hylé Developer Hub
site_url: https://docs.hyle.eu
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    primary: custom
  features:
    - navigation.sections # section titles in left-hand menu
    - navigation.indexes # clickable section titles in left-hand menu
    - navigation.expand # expand sub-menus (re-enable if header tabs)
  #  - navigation.tabs # to have header tabs
    - navigation.prune # html minimization
  #  - toc.integrate # toc in left-hand sidebar
    - content.code.copy
    - navigation.footer

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - mkdocs-video
  - social:
      cards_layout_options:
        color: "#E0482E"

copyright: Copyright &copy; 2024 Hylé

extra:
  social:
    - icon: fontawesome/brands/github
      link: http://github.com/hyle-org/
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/hyle_org
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/hyl-/
    - icon: fontawesome/solid/archway
      link: https://warpcast.com/hyle-org
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Hyl%C3%A9-org
    - icon: fontawesome/brands/telegram
      link: https://t.me/hyle_org

repo_url: https://github.com/Hyle-org/hyle
