name: Publish MkDocs Documentation

permissions:
  contents: write

on:
  push:
    branches:
      - main  # Déclenche l'action uniquement sur la branche principale
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-awesome-pages-plugin
          pip install mkdocs mkdocs-material
          pip install mkdocs-video

      - name: Setup git user 
        run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Publish doc 
        run: |
          mkdocs gh-deploy
